# Параметры подключения к Zabbix API
zabbix_api_url: "http://{{ hostvars['zabbix']['ansible_host'] }}/zabbix/api_jsonrpc.php"
zabbix_user: "Admin"
zabbix_password: "zabbix"

# Группа и шаблон по умолчанию
zabbix_hostgroup_name: "Linux servers"
zabbix_template_name: "Linux by Zabbix agent"

